In [1]:
import numpy as np

In [2]:
list_wt = [46, 56, 78, 87, 67]

In [6]:
type(list_wt)

list

#### creation of numpy array

In [3]:
list_numpy = np.array([46, 56, 78, 87, 67])

In [4]:
print(list_numpy)

[46 56 78 87 67]


In [5]:
type(list_numpy)

numpy.ndarray

#### create numpy array from list

In [8]:
list_conv = np.array(list_wt)

In [9]:
type(list_conv)

numpy.ndarray

In [10]:
list_conv

array([46, 56, 78, 87, 67])

In [18]:
list_conv.shape

(5,)

In [19]:
list_conv.ndim

1

In [12]:
list_conv.dtype

dtype('int32')

In [13]:
new_1 = np.array(['A', 'B'])

In [15]:
new_1.dtype

dtype('<U1')

In [20]:
new_1.ndim

1

### 2 D array

In [16]:
two_d_array = np.array([[5, 2, 4], [9, 1, 1]])

In [17]:
print(two_d_array)

[[5 2 4]
 [9 1 1]]


In [21]:
two_d_array.shape

(2, 3)

In [26]:
two_d_array[0][2]

4

In [23]:
two_d_array[1]

array([9, 1, 1])

In [27]:
matrix_ = np.array([[1, 2, 3], [4, 5 , 6], [7, 8 , 9]])

In [28]:
matrix_.shape

(3, 3)

### few other ways to create array-numpy 

In [29]:
mat_zero = np.zeros(shape = (3, 5))

In [30]:
mat_zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
mat_zero = np.zeros(shape = (3, 5), dtype = 'int')

In [33]:
mat_zero

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [34]:
mat_zero.shape

(3, 5)

In [35]:
mat_one = np.ones(shape = (3, 5), dtype = 'int')

In [36]:
mat_one

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [37]:
np.zeros(shape = (5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [42]:
type(mat_one[1][3])

numpy.int32

In [43]:
mat_full = np.full(shape = (4, 4),fill_value=8)

In [44]:
mat_full

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [48]:
np.full((5, 4), 101)

array([[101, 101, 101, 101],
       [101, 101, 101, 101],
       [101, 101, 101, 101],
       [101, 101, 101, 101],
       [101, 101, 101, 101]])

In [50]:
np.full(shape = (5,4), fill_value = 101)

array([[101, 101, 101, 101],
       [101, 101, 101, 101],
       [101, 101, 101, 101],
       [101, 101, 101, 101],
       [101, 101, 101, 101]])

In [51]:
np.full((5, 4), fill_value = 101)

array([[101, 101, 101, 101],
       [101, 101, 101, 101],
       [101, 101, 101, 101],
       [101, 101, 101, 101],
       [101, 101, 101, 101]])

In [52]:
help(np.full)

Help on function full in module numpy:

full(shape, fill_value, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with `fill_value`.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar or array_like
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, None, means
         ``np.array(fill_value).dtype``.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that pas

#### intitalizing with random values